databases:
  - name: dress-me-db
    plan: free
    databaseName: dressme
    user: dressme

services:
  - type: web
    name: dress-me-api
    plan: free
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: dress-me-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://client-gold-two-81.vercel.app
      - key: REDIS_URL
        value: ""
