/**
 * Live Effects — Lottie asset registry.
 *
 * Maps catalog gift ids and subscriber tiers to their Lottie animation data.
 * These are procedural STARTER assets (src/assets/lottie/*.json, generated by
 * scripts/gen-lottie.mjs) — swap the JSON files to rebrand an effect without
 * any code change. Imported only by the lazy LottieEffectsLayer so the JSON
 * never ships in the initial bundle.
 */
import heart from '@/assets/lottie/heart.json';
import rose from '@/assets/lottie/rose.json';
import star from '@/assets/lottie/star.json';
import spotlight from '@/assets/lottie/spotlight.json';
import entranceVip from '@/assets/lottie/entrance-vip.json';
import entranceInner from '@/assets/lottie/entrance-inner.json';

// Lottie animationData is an opaque JSON blob to us; keep it loosely typed.
type LottieData = Record<string, unknown>;

/** Catalog gift id → Lottie data. Note: catalog id `outfit` (label "Star") maps to the star burst. */
const GIFT_LOTTIE: Record<string, LottieData> = {
  heart: heart as LottieData,
  rose: rose as LottieData,
  outfit: star as LottieData,
  spotlight: spotlight as LottieData,
};

/** Subscriber tier → entrance flourish Lottie. */
const ENTRANCE_LOTTIE: Record<string, LottieData> = {
  VIP: entranceVip as LottieData,
  INNER_CIRCLE: entranceInner as LottieData,
};

export function getGiftLottie(giftId: string): LottieData | null {
  return GIFT_LOTTIE[giftId] ?? null;
}

export function getEntranceLottie(tier: string): LottieData | null {
  return ENTRANCE_LOTTIE[tier] ?? null;
}
